#!/bin/bash

# Colors

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

NC="\e[0m"

PROMPT="${RED}$USER${BLUE}@${P}onion: ${NC}"

help(){
echo -e "\n${RED}======================================================="
echo -e "\n${RED}========== ${YELLOW}Welcome to the The Onion Shell${RED} ============="
echo -e "\n======================================================="
echo -e "\n${GREEN}<---- Which only speaks TheOnionBox commands btw --->${NC}"
echo -e "\n${BLUE}[${GREEN} COMMANDS ${BLUE}]${NC}"
echo -e "\n${BLUE}[${GREEN}1${BLUE}]${GREEN} start"
echo -e "\n${BLUE}[${GREEN}2${BLUE}]${GREEN} stop"
echo -e "\n${BLUE}[${GREEN}3${BLUE}]${GREEN} restart"
echo -e "\n${BLUE}[${GREEN}4${BLUE}]${GREEN} myip"
echo -e "\n${BLUE}[${GREEN}5${BLUE}]${GREEN} changeid"
echo -e "\n${BLUE}[${GREEN}6${BLUE}]${GREEN} boot-enable"
echo -e "\n${BLUE}[${GREEN}7${BLUE}]${GREEN} boot-disable"
echo -e "\n${BLUE}[${GREEN}8${BLUE}]${GREEN} reset-config"
echo -e "\n${BLUE}[${GREEN}9${BLUE}]${GREEN} show-config${NC}"
echo -e "\n${BLUE}[${GREEN}INFO${BLUE}]${GREEN} Note: type ${YELLOW}'exit' to kill current shell${NC}"
}

help

while true; do

   echo -e -n $PROMPT
   read -r user_input

   if [[ -z "$user_input" ]]; then
       continue
   fi
   
   if [[ "$user_input" == "exit" ]]; then
       break
   fi

   if [[ "$user_input" == "start" ]]; then
       onionbox start
       shift
       wait
   fi
   
   if [[ "$user_input" == "stop" ]]; then
       onionbox stop
       shift
       wait
   fi

   if [[ "$user_input" == "restart" ]]; then
       onionbox restart
       shift
       wait
   fi
   
   if [[ "$user_input" == "myip" ]]; then
       onionbox myip
       shift
       wait
   fi
   
   if [[ "$user_input" == "changeid" ]]; then
       onionbox changeid
       shift
       wait
   fi

   if [[ "$user_input" == "boot-enable" ]]; then
       onionbox --boot-enable
       shift
       wait
   fi

   if [[ "$user_input" == "boot-disable" ]]; then
         onionbox --boot-disable
	 shift
	 wait
   fi

   if [[ "$user_input" == "reset-config" ]]; then
         onionbox --reset-config
	 shift
	 wait
   fi

   if [[ "$user_input" == "show-config" ]]; then
         onionbox --show-config
         shift
	 wait
   fi

   if [[ "$user_input" == "help" ]]; then
         help
	 shift
	 wait
   fi

   eval "$user_input" >/dev/null 2>&1
   echo ""
done
