#!/bin/sh

# Colors

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

WHITE="\e[1;37m"

YELLOW="\e[1;33m"

NC="\e[0m"

# Aliases and trap

trap 'exit 1' INT SIGINT TERM

# Dependencies && pkg managers

if ! (command -v nc >/dev/null 2>&1 && command -v git >/dev/null 2>&1 && command -v curl >/dev/null 2>&1 && command -v tor >/dev/null 2>&1 && command -v iptables >/dev/null 2>&1 && command -v NetworkManager >/dev/null 2>&1 && command -v bash >/dev/null 2>&1 && command -v nft >/dev/null 2>&1 && command -v pkill >/dev/null 2>&1 && command -v nyx >/dev/null 2>&1); then
    pkgs=( openbsd-netcat curl tor iptables iproute2 networkmanager e2fsprogs coreutils util-linux bash iptables-nft nftables sudo nyx )

      if [[ $(command -v apt) ]]; then
           if ! apt-get update && apt install "${pkgs[@]}" -y; then
	       echo -e "${RED}[${WHITE}X${RED}]${WHITE} Missing deps, please, manually install (${pkgs[@]})${NC}"
	       exit 1
	   fi
	   wait

      elif [[ $(command -v pacman) ]]; then
            if ! pacman -Syy "${pkgs[@]}" --noconfirm --overwrite "*"; then
		echo -e "${RED}[${WHITE}X${RED}]${WHITE} Missing deps, please, manually install (${pkgs[@]})${NC}"
	        exit 1
	    fi
	    wait

      elif [[ $(command -v dnf) ]]; then
            if ! dnf -y install "${pkgs[@]}"; then
	        echo -e "${RED}[${WHITE}X${RED}]${WHITE} Missing deps, please, manually install (${pkgs[@]})${NC}"
	        exit 1
	    fi
	    wait

      elif [[ $(command -v yum) ]]; then
            if ! yum -y install "${pkgs[@]}"; then
	         echo -e "${RED}[${WHITE}X${RED}]${WHITE} Missing deps, please, manually install (${pkgs[@]})${NC}"
	         exit 1
	    fi
	    wait

      elif [[ $(command -v zypper) ]]; then
            if ! zypper install "${pkgs[@]}"; then
	         echo -e "${RED}[${WHITE}X${RED}]${WHITE} Missing deps, please, manually install (${pkgs[@]})${NC}"
	         exit 1
	    fi
	    wait

      elif [[ $(command -v apk) ]]; then
            if ! apk add "${pkgs[@]}"; then
	        echo -e "${RED}[${WHITE}X${RED}]${WHITE} Missing deps, please, manually install (${pkgs[@]})${NC}"
	        exit 1
	    fi
	    wait

      elif [[ $(command -v xbps-install) ]]; then
            if ! xbps-install -S "${pkgs[@]}"; then
	        echo -e "${RED}[${WHITE}X${RED}]${WHITE} Missing deps, please, manually install (${pkgs[@]})${NC}"
	        exit 1
	    fi
	    wait

      elif [[ $(command -v pkg) ]]; then
            if ! pkg install "${pkgs[@]}"; then
	        echo -e "${RED}[${WHITE}X${RED}]${WHITE} Missing deps, please, manually install (${pkgs[@]})${NC}"
	        exit 1
	    fi
	    wait

      elif [[ $(command -v flatpak) ]]; then
            if ! flatpak install "${pkgs[@]}"; then
	        echo -e "${RED}[${WHITE}X${RED}]${WHITE} Missing deps, please, manually install (${pkgs[@]})${NC}"
	        exit 1
	    fi
	    wait
      else
            echo -e "\n${RED}[${WHITE}!${RED}]${NC} Unsuported Package Manager, Install dependencies ${RED}manually.${NC}"
            echo -e "\n${RED}[${WHITE}!${RED}]${NC} Needed: ${pkgs[@]}${NC}"
            exit 1
      fi
fi

# Service Managers && Boot Automation

if [ ! -f /etc/systemd/system/tonion.service ] && command -v systemctl >/dev/null 2>&1; then
    touch /etc/systemd/system/tonion.service
    cat << 'EOT' > /etc/systemd/system/tonion.service
    [Unit]
    Description=Secure Proxy through Tor's network
    [Service]
    Type=forking
    ExecStart=tonion start
    RemainAfterExit=yes
    User=root
    [Install]
    WantedBy=multi-user.target
EOT

elif [ ! -f /etc/sv/tonion/run ] && command -v runit >/dev/null 2>&1; then
      mkdir -p /etc/sv/tonion/
      touch /etc/sv/tonion/run
      cat << 'EOT' > /etc/sv/tonion/run
      #!/bin/sh
      exec tonion start
EOT
      chmod +x /etc/sv/tonion/run

elif [ ! -f /etc/init.d/tonion ] && command -v rc-service >/dev/null 2>&1; then
      touch /etc/init.d/tonion
      cat << 'EOT' > /etc/init.d/tonion
      #!/sbin/openrc-run
      name=tonion start service
      command="tonion"
      command_args="start"
      command_background=true
      pidfile="/run/${RC_SVCNAME}.pid"
      depend() {
         need net
      }
EOT
      chmod +x /etc/init.d/tonion
fi

# Torrc && Script Functions

if ! $(tor --verify-config >/dev/null 2>&1); then

echo -e "\n${RED}[${NC}*${RED}]${NC} Tor configuration file is not valid, so... it cannot start.. You should try 'tonion -rc'"

fi

help(){
   echo -e "\n${P}[${NC} Tool Actions ${P}]${NC}"
   echo -e "\n${P}[${NC}0${P}]${NC} --start|-start|start|0: ${GREEN}Starts Tor and apply Firewall rules${NC}"
   echo -e "\n${P}[${NC}1${P}]${NC} --stop|-stop|stop|1: ${GREEN}Stops Tor and restart Firewall rules to default's${NC}"
   echo -e "\n${P}[${NC}2${P}]${NC} --restart|-restart|restart|-r: ${GREEN}Restarts Tor and Firewall rules${NC}"
   echo -e "\n${P}[${NC}3${P}]${NC} --status|-status|-s: ${GREEN}Launches nyx'x Tor process real time viewer(TUI based)${NC}"
   echo -e "\n${P}[${NC}4${P}]${NC} --boot-enable|-boot-enable|boot-enable: ${GREEN}Disables start's action on boot ${NC}"
   echo -e "\n${P}[${NC}5${P}]${NC} --boot-disable|-boot-disable|boot-disable: ${GREEN}Enables start's action on boot ${NC}"
   echo -e "\n${P}[${NC}6${P}]${NC} --myip|-myip|myip|-i: ${GREEN}Prints Tor's IP Address${NC}"
   echo -e "\n${P}[${NC}7${P}]${NC} --change|-change|change|-c: ${GREEN}Changes Tor's IP Address${NC}"
   echo -e "\n${P}[${NC}8${P}]${NC} --fix|-fix|fix|-f: ${GREEN}Fixes your internet connection(not trough tor, can expose your IP address) ${NC}"
   echo -e "\n${P}[${NC}9${P}]${NC} --set-bridges|-set-bridges|-b: usage: ${GREEN}tonion -b ${NC}</path/to/bridges/file> <bridges_kind> </path/to/binary>"
   echo -e "\n${P}[${NC}10${P}]${NC} --restart-torrc|-restart-torrc|-rc: ${GREEN}Is in the name, restarts /etc/tor/torrc ${GREEN}to tool's default ${NC}"
   echo -e "\n${P}[${NC}11${P}]${NC} --help|-help|help|-h: ${GREEN}Prints this help page${NC}"
}

myip(){

export agent=( 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Edg/148.0.3967.83' )

if pgrep -af tor >/dev/null 2>&1 || ss -tulpn | grep -iE "127.0.0.1|5353|9040|9050|9051" >/dev/null 2>&1; then

   echo -e "\n${BLUE}[${WHITE}+${BLUE}]${P} Your Tor IP${NC}:"

   curl --socks5-hostname 127.0.0.1:9050 --user-agent "${agent[$RANDOM % ${#agent[@]}]}" https://check.torproject.org/api/ip

   echo -e "\n${BLUE}[${WHITE}*${BLUE}]${P} Your Tor ISP/Node info${NC}:"
   
   curl 'ip-api.com?fields=country,countryCode,as,org,asname,proxy,city,region,regionName,isp,currency'

else
   
   echo -e "\n${RED}[${WHITE}-${RED}]${NC} Public IP ${RED}(which is not from Tor btw)${NC}:"

   curl --user-agent "${agent[$RANDOM % ${#agent[@]}]}" https://check.torproject.org/api/ip

   echo -e "\n${RED}[${WHITE}*${RED}]${NC} Your ISP is${NC}:"
 
   curl 'ip-api.com?fields=country,countryCode,as,org,asname,proxy,city,region,regionName,isp,currency'
fi

}

start(){

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${WHITE}-${RED}]${NC} Perform this action as ${RED}root${NC}"
    exit 1
fi

if ss -tulpn | grep -iE "127.0.0.1|5353|9040|9050|9051" >/dev/null 2>&1 || pgrep -af tor >/dev/null 2>&1; then
   echo -e "\n${P}[${WHITE}*${P}]${NC} Tor is running, no need to type 'start'"
   myip
   exit 1
fi

   mods=( ip_tables iptable_filter x_tables xt_conntrack ipt_REJECT iptable_mangle iptable_nat ipt_MASQUERADE nft_tables )

   for i in "${mods[@]}"; do
         lsmod | grep "$i" >/dev/null 2>&1 || modprobe $i >/dev/null 2>&1
   done

   sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null 2>&1

   sysctl -w net.ipv4.icmp_echo_ignore_all=1 >/dev/null 2>&1

   sysctl -w net.ipv6.icmp.echo_ignore_all=1 >/dev/null 2>&1

   sysctl -w net.ipv6.conf.lo.disable_ipv6=1 >/dev/null 2>&1

   sysctl --system >/dev/null 2>&1

   pkill -9 tor NetworkManager >/dev/null 2>&1

   chattr -i /etc/resolv.conf >/dev/null 2>&1

   rm /etc/resolv.conf >/dev/null 2>&1
   touch /etc/resolv.conf >/dev/null 2>&1

   echo "nameserver 127.0.0.1" | tee /etc/resolv.conf >/dev/null 2>&1

   chmod 644 /etc/resolv.conf >/dev/null 2>&1

   chattr +i /etc/resolv.conf >/dev/null 2>&1

   echo -e "\n${GREEN}[${NC}+${GREEN}] ${NC}Tor is starting, please wait..${NC}"

   NetworkManager >/dev/null 2>&1

   sleep 4

   sudo -u $TOR_USER tor --RunAsDaemon 1 >/dev/null 2>&1

   sudo ip6tables -F >/dev/null 2>&1

   sudo ip6tables -t nat -F >/dev/null 2>&1

   sudo ip6tables -t mangle -F >/dev/null 2>&1

   sudo ip6tables -A INPUT -p icmpv6 --icmpv6-type echo-request -j DROP >/dev/null 2>&1

   sudo ip6tables -P INPUT DROP >/dev/null 2>&1

   sudo ip6tables -P FORWARD DROP >/dev/null 2>&1

   sudo ip6tables -P OUTPUT DROP >/dev/null 2>&1

   sudo iptables -F >/dev/null 2>&1

   sudo iptables -X >/dev/null 2>&1

   sudo iptables -A INPUT -i lo -j ACCEPT >/dev/null 2>&1

   sudo iptables -A OUTPUT -o lo -j ACCEPT >/dev/null 2>&1

   sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT >/dev/null 2>&1

   sudo iptables -A OUTPUT -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT >/dev/null 2>&1

   sudo iptables -A INPUT -i lo -p icmp --icmp-type echo-request -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT >/dev/null 2>&1

   sudo iptables -A OUTPUT -o lo -p icmp --icmp-type echo-request -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT >/dev/null 2>&1

   sudo iptables -A INPUT -p icmp --icmp-type echo-request -j DROP >/dev/null 2>&1

   sudo iptables -A OUTPUT -p icmp --icmp-type echo-request -j DROP >/dev/null 2>&1

   sudo iptables -A OUTPUT -m owner --uid-owner $TOR_USER -j ACCEPT >/dev/null 2>&1

   sudo iptables -A OUTPUT -p udp -d 127.0.0.1 --dport 5353 -j ACCEPT >/dev/null 2>&1

   sudo iptables -A OUTPUT -p tcp -d 127.0.0.1 --dport 9040 -j ACCEPT >/dev/null 2>&1

   sudo iptables -A OUTPUT -j REJECT >/dev/null 2>&1

   sudo iptables -t nat -F >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_USER -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 127.0.0.0/8 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 192.168.0.0/16 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 10.0.0.0/8 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 172.16.0.0/12 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 169.254.0.0/16 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 255.255.255.255/32 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 224.0.0.0/4 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 5353 >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports 9040 >/dev/null 2>&1

   sudo iptables -t nat -I OUTPUT -d 127.0.0.1 -p udp --dport 53 -j REDIRECT --to-ports 5353 >/dev/null 2>&1

   sudo iptables -t nat -I OUTPUT -d 127.0.0.1 -p tcp --dport 53 -j REDIRECT --to-ports 5353 >/dev/null 2>&1

   sudo iptables -P OUTPUT DROP >/dev/null 2>&1

   sudo iptables -P INPUT DROP >/dev/null 2>&1

   sudo iptables -P FORWARD DROP >/dev/null 2>&1

   myip

}

config(){

if ! cat /etc/tor/torrc | grep -iE "UseBridges 1" >/dev/null 2>&1; then
   rm /etc/tor/torrc >/dev/null 2>&1
   touch /etc/tor/torrc >/dev/null 2>&1
   cat << 'EOT' > /etc/tor/torrc
   CookieAuthentication 0
   VirtualAddrNetworkIPv4 10.192.0.0/10
   AutomapHostsOnResolve 1
   AutomapHostsSuffixes .exit,.onion
   TransPort 127.0.0.1:9040
   DNSPort 127.0.0.1:5353
   ControlPort 9051
   EntryNodes {is},{ch},{fi},{ro}
   ExitNodes {is},{ch},{fi},{ro}
   StrictNodes 1
   MaxCircuitDirtiness 20
   ClientUseIPv6 0
   ClientPreferIPv6ORPORT 0
   ClientRejectInternalAddresses 1
EOT

fi
   if id debian-tor >/dev/null 2>&1; then
       export TOR_USER="debian-tor"
       echo -e "\n${BLUE}[${NC}*${BLUE}]${NC} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   elif id tor >/dev/null 2>&1; then
       export TOR_USER="tor"
       echo -e "\n${BLUE}[${NC}*${BLUE}]${NC} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   elif id toranon >/dev/null 2>&1; then
       export TOR_USER="toranon"
       echo -e "\n${BLUE}[${NC}*${BLUE}]${NC} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   elif echo $TOR_USER >/dev/null 2>&1; then
       echo -e "\n${BLUE}[${NC}*${BLUE}]${NC} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   else
        echo -e "\n${RED}[${NC}-${RED}]${NC} Script needs a tor user to apply fireall rules and we couldnt find it${NC}, you should manually check it by typing: ${GREEN}'id tor'${NC}, then do this: ${GREEN}export TOR_USER='your_tor_user_output', or manually create an user 'tor'${NC}"
        exit 1
   fi

   chown -R $TOR_USER:$TOR_USER /etc/tor/torrc >/dev/null 2>&1
   chown -R $TOR_USER:$TOR_USER /var/lib/tor >/dev/null 2>&1
   start
}

function stop(){

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${NC}-${RED}]${NC} Perform this action as ${RED}root${NC}"
    exit 1
fi

if ss -tulpn | grep -iE "tor|127.0.0.1|5353|9040|9050|9051" >/dev/null 2>&1 || pgrep -af tor >/dev/null 2>&1; then

   echo -e "\n${RED}[${NC}-${RED}]${NC} Killing Tor.."
   
   pkill -9 tor NetworkManager >/dev/null 2>&1

   chattr -i /etc/resolv.conf >/dev/null 2>&1

   rm /etc/resolv.conf >/dev/null 2>&1
   touch /etc/resolv.conf >/dev/null 2>&1

   echo "nameserver 9.9.9.9" | tee /etc/resolv.conf >/dev/null 2>&1

   chattr +i /etc/resolv.conf >/dev/null 2>&1

   NetworkManager >/dev/null 2>&1

   sleep 4

   sysctl -w net.ipv6.conf.all.disable_ipv6=0 >/dev/null 2>&1

   sysctl -w net.ipv4.icmp_echo_ignore_all=0 >/dev/null 2>&1

   sysctl -w net.ipv6.icmp.echo_ignore_all=0 >/dev/null 2>&1

   sysctl -w net.ipv6.conf.lo.disable_ipv6=0 >/dev/null 2>&1

   sysctl --system >/dev/null 2>&1

   mods=( ip_tables iptable_filterx_tables nf_conntrack xt_conntrack ipt_REJECT iptable_mangle nf_nat iptable_nat ipt_MASQUERADE )
   for i in "${mods[@]}"; do
       lsmod | grep $i >/dev/null 2>&1 || modprobe $i >/dev/null 2>&1
   done

   sudo ip6tables -F >/dev/null 2>&1

   sudo ip6tables -t nat -F >/dev/null 2>&1

   sudo ip6tables -t mangle -F >/dev/null 2>&1

   sudo ip6tables -P INPUT ACCEPT >/dev/null 2>&1

   sudo ip6tables -P FORWARD ACCEPT >/dev/null 2>&1

   sudo ip6tables -P OUTPUT ACCEPT >/dev/null 2>&1

   sudo iptables -F >/dev/null

   sudo iptables -X >/dev/null

   sudo iptables -t nat -X >/dev/null

   sudo iptables -t nat -F >/dev/null

   sudo iptables -P INPUT ACCEPT >/dev/null

   sudo iptables -P FORWARD ACCEPT >/dev/null

   sudo iptables -P OUTPUT ACCEPT >/dev/null

   myip

else
   echo -e "\n${RED}[${WHITE}-${RED}]${NC} And Tor is not even running..."
   exit 1
fi

}


# Function Calls (parameters)

while [ $# -gt 0 ]; do

case $1 in

--start|-start|start|0)

mode=1

if [ -d /data/data/com.termux/ ] && ! pgrep tor >/dev/null 2>&1 || ss -tulpn | grep -iE "127.0.0.1|5353|9040|9050|9051" >/dev/null 2>&1; then
    echo -e "\n${GREEN}[${NC}+${GREEN}] ${NC}Tor is starting, please wait..${NC}"         pkill -9 NetworkManager >/dev/null 2>&1

     [ -d /data/data/com.termux/files/usr/etc/ ] && rm /data/data/com.termux/files/usr/etc/resolv.conf >/dev/null 2>&1 && touch /data/data/com.termux/files/usr/etc/resolv.conf >/dev/null 2>&1 && echo "nameserver 127.0.0.1" | tee /data/data/com.termux/files/usr/etc/resolv.conf >/dev/null 2>&1

     if [ -d /data/data/com.termux/files/usr/etc/tor/ ]; then
         if ! cat /data/data/com.termux/file/usr/etc/tor/torrc | grep -iE "UseBridges 1" >/dev/null 2>&1; then
            cat << 'EOT' > /data/data/com.termux/file/usr/etc/tor/torrc                                                 
	        CookieAuthentication 0           
		VirtualAddrNetworkIPv4 10.192.0.0/10                 
	        AutomapHostsOnResolve 1                              
		AutomapHostsSuffixes .exit,.onion                    
		TransPort 127.0.0.1:9040                             
                DNSPort 127.0.0.1:5353                               
		ControlPort 9051                                     
		EntryNodes {is},{ch},{fi},{ro}                       
		ExitNodes {is},{ch},{fi},{ro}                        
		StrictNodes 1                                        
		MaxCircuitDirtiness 20                               
		ClientUseIPv6 0                                     
		ClientPreferIPv6ORPORT 0                             
		ClientRejectInternalAddresses 1
EOT
              NetworkManager >/dev/null 2>&1
              tor -f /data/data/com.termux/file/usr//etc/tor/torrc --RunAsDaemon 1 >/dev/null 2>&1
             myip
	     exit 0
         fi
        
         NetworkManager >/dev/null 2>&1                       
	 tor --RunAsDaemon 1 >/dev/null 2>&1                      
	 myip                                                 
	 exit 0
        
    fi
else
      echo -e "\n${P}[${WHITE}*${P}]${NC} Tor is already running, no need to try start it again"
      myip
      exit 0

shift 
break
fi

config

shift

break

;;

--stop|-stop|stop|1)

mode=2

if [ -d /data/data/com.termux/files/ ]; then
    pkill -9 tor >/dev/null
    echo -e "\n${RED}[${NC}*${RED}]${NC} Tor stopped"
    exit 0
fi

stop

shift

break

;;

--myip|-myip|myip|-i)

mode=4

myip

shift

break

;;

change|--change|-change|-c)

mode=5

if ss -tulpn | grep -iE "127.0.0.1|5353|9040|9050|9051" >/dev/null 2>&1 || pgrep -af tor >/dev/null 2>&1; then

   echo -e "\n${BLUE}[${NC}!${BLUE}]${P} Changing Tor IP..${NC}"

   echo -e "AUTHENTICATE \"\"\nSIGNAL NEWNYM\nQUIT" | nc 127.0.0.1 9051 >/dev/null 2>&1
   
   echo -e "\n${BLUE}[${NC}*${BLUE}]${P} Your changed IP Address is: ${NC}"
   
   myip

else
   echo -e "\n${RED}[${NC}Err${RED}]${NC} And.. Tor is not even running.."
   exit 1
fi

shift

break

;;

boot-enable|--boot-enable|-boot-enable)

mode=6

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${NC}-${RED}]${NC} A password is required to manage services, please, run this as ${RED}root${NC}"
    exit 1
fi

if [ -f /etc/systemd/system/tonion.service ] && command -v systemctl >/dev/null 2>&1; then

    if systemctl is-enabled tonion >/dev/null 2>&1; then
       echo -e "\n${P}[${WHITE}*${P}]${NC} tonion is already enable"
       exit 0
    fi

    if systemctl enable tonion >/dev/null 2>&1; then
       echo -e "\n${GREEN}[${WHITE}+${GREEN}]${NC} tonion has been enabled"
       exit 0
    else
       echo -e "\n${RED}[${WHITE}-${RED}]${NC} could not enable tonion, check your permissions over the system"
       exit 1
    fi

elif [ -f /etc/sv/tonion/run ] && command -v runit  >/dev/null 2>&1; then
      if ls -l /var/service/tonion/ >/dev/null 2>&1; then
            echo -e "\n${P}[${WHITE}*${P}]${NC} tonion is already enable"
            exit 0
      fi

      if ln -s /etc/sv/tonion /var/service/ >/dev/null 2>&1; then
           echo -e "\n${GREEN}[${WHITE}+${GREEN}]${NC} tonion has been enabled"
           exit 0
      else
           echo -e "\n${RED}[${WHITE}-${RED}]${NC} could not enable tonion, check your permissions over the system"
           exit 1
      fi

elif [ -f /etc/init.d/tonion/ ] && command -v rc-service  >/dev/null 2>&1; then

      if rc-update | grep -iE "tonion" >/dev/null 2>&1; then
           echo -e "\n${P}[${WHITE}*${P}]${NC} tonion is already enable"
           exit 0
      fi

      if rc-update add tonion default >/dev/null 2>&1; then
           echo -e "\n${GREEN}[${WHITE}+${GREEN}]${NC} tonion has been enabled"
           exit 0
      else
           echo -e "\n${RED}[${WHITE}-${RED}]${NC} could not enable tonion, check your permissions over the system"
           exit 1
      fi
fi

shift
break
;;

boot-disable|--boot-disable|-boot-disable)

mode=7

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${WHITE}-${RED}]${NC} A password is required to manage services, please, run this as ${RED}root${NC}"
    exit 1
fi

if [ -f /etc/systemd/system/tonion.service ] && command -v systemctl >/dev/null 2>&1; then

    if ! systemctl is-enabled tonion >/dev/null 2>&1; then
       echo -e "\n${P}[${WHITE}*${P}]${NC} tonion is already disable"
       exit 0
    fi

    if systemctl disable tonion >/dev/null 2>&1; then
       echo -e "\n${GREEN}[${WHITE}+${GREEN}]${NC} tonion has been disabled"
       exit 0
    else
       echo -e "\n${RED}[${WHITE}-${RED}]${NC} could not disable tonion, check your permissions over the system"
       exit 1
    fi

elif [ -f /etc/sv/tonion/run ] && command -v runit  >/dev/null 2>&1; then
      if ! ls -l /var/service/tonion/ >/dev/null 2>&1; then
           echo -e "\n${P}[${WHITE}*${P}]${NC} tonion is already disabled"
           exit 0
      fi

      if rm /var/service/tonion >/dev/null 2>&1; then
           echo -e "\n${GREEN}[${WHITE}+${GREEN}]${NC} tonion has been disabled"
           exit 0
      else
           echo -e "\n${RED}[${WHITE}-${RED}]${NC} could not disable tonion. check your permissions over the system"
           exit 1
      fi

elif [ -f /etc/init.d/tonion/ ] && command -v rc-service  >/dev/null 2>&1; then

      if ! rc-update | grep -iE "tonion" >/dev/null 2>&1; then
           echo -e "\n${P}[${WHITE}*${P}]${NC} tonion is already disabled"
           exit 0
      fi

      if rc-update del tonion default >/dev/null 2>&1; then
           echo -e "\n${RED}[${WHITE}+${RED}]${NC} tonion has been disable"
           exit 0
      else
           echo -e "\n${RED}[${WHITE}-${RED}]${NC} could not disable tonion, check your permissions over the system"
           exit 1
      fi
fi

shift
break
;;

--fix|-fix|fix|-f)
mode=8

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${WHITE}*${RED}]${NC} A password is required for this action, please run this as ${RED}root${NC}"
    exit 1
fi

echo -e "\n${BLUE}[${WHITE}!${BLUE}]${NC} Fixing your internet connection, ${RED}(killing Tor, flushing firewall rules)${NC}"

  pkill -9 tor >/dev/null 2>&1

  chattr -i /etc/resolv.conf >/dev/null 2>&1

  rm /etc/resolv.conf >/dev/null 2>&1
  
  touch /etc/resolv.conf >/dev/null 2>&1
  
  echo "nameserver 9.9.9.9" |   tee /etc/resolv.conf >/dev/null 2>&1
  
  chattr +i /etc/resolv.conf >/dev/null 2>&1

  NetworkManager >/dev/null 2>&1

  sysctl -w net.ipv6.conf.all.disable=0 >/dev/null 2>&1

  sysctl -w net.ipv6.conf.default.disable=0 >/dev/null 2>&1

  sysctl -w net.ipv6.conf.lo.disable=0 >/dev/null 2>&1

  sysctl --system >/dev/null 2>&1

  ip6tables -F >/dev/null 2>&1

  ip6tables -t nat -F >/dev/null 2>&1

  ip6tables -t mangle -F >/dev/null 2>&1

  ip6tables -P INPUT ACCEPT >/dev/null 2>&1

  ip6tables -P FORWARD ACCEPT >/dev/null 2>&1

  ip6tables -P OUTPUT ACCEPT >/dev/null 2>&1

  iptables -F >/dev/null

  iptables -X >/dev/null

  iptables -t nat -X >/dev/null

  iptables -t nat -F >/dev/null

  iptables -P INPUT ACCEPT >/dev/null

  iptables -P FORWARD ACCEPT >/dev/null

  iptables -P OUTPUT ACCEPT >/dev/null

  myip

shift
break
;;

--set-bridges|-set-bridges|-b)
mode=9
file=$2
kind=$3
bin=$4

rm /etc/tor/torrc >/dev/null 2>&1
touch /etc/tor/torrc >/dev/null 2>&1

if [[ -z "$file" || ! -f "$file" || -z "$kind" || ! "$bin" || -z "$bin" ]]; then
    echo -e "\n${BLUE}[${WHITE}!${BLUE}]${NC} Use: ${GREEN}tonion --set-bridges </path/to/your_bridges_file> <bridges_kind> </path/to/your/proxy/bin>${NC}"
    echo -e "\n${BLUE}[${WHITE}!${BLUE}]${NC} EXAMPLE: ${GREEN}tonion -b my_bridges.txt obfs4 /usr/bin/obfs4proxy${NC}"
    echo -e "\n${BLUE}[${WHITE}!${BLUE}]${NC} Ensure file has ONLY the bridges and is following a correct format, Example of correct of a bridge format on file: ${YELLOW}<${NC}Prefix: ${YELLOW}'bridge'> <${NC}type${YELLOW}> [${NC}IP${YELLOW}]${NC}:${YELLOW}[${NC}PORT${YELLOW}] [${NC}fingerprint${YELLOW}] [${NC}Key=value${YELLOW}]${NC}"
    echo -e "\n${RED}[${WHITE}-${RED}]${NC} Warn, you see this page because something failed ${RED}(mb you forget to give some params)${NC}"
    exit 1
fi

bridges=$(cat "$file")

echo -e "\nCookieAuthentication 0\nVirtualAddrNetworkIPv4 10.192.0.0/10\nAutomapHostsOnResolve 1\nAutomapHostsSuffixes .exit,.onion\nTransPort 127.0.0.1:9040\nDNSPort 127.0.0.1:5353\nControlPort 9051\nClientTransportPlugin $kind exec $bin\n$bridges\nUseBridges 1\nClientUseIPv6 0\nClientPreferIPv6ORPORT 0\nClientRejectInternalAddresses 1" | tee /etc/tor/torrc >/dev/null 2>&1

if tor --verify-config >/dev/null 2>&1; then
   echo -e "\n${P}[${WHITE}*${P}]${NC} Seems like your bridges are okay, try ${GREEN}'tonion start/restart(if a current instance of the script is running)'${NC}"
   chown -R $TOR_USER:$TOR_USER /etc/tor/torrc
   chown -R $TOR_USER:$TOR_USER /var/lib/tor
   exit 0
else
   echo -e "\n${RED}[${WHITE}-${RED}]${NC} Tor config is not valid.. Run 'cat /etc/tor/torrc', or give a valid configuration file"
   exit 1
fi

shift
break

;;

--restart-torrc|-restart-torrc|-rc)
mode=10
   echo -e "\n${BLUE}[${WHITE}*${BLUE}]${NC} Reseting Tor's configuration file to default's"
   rm /etc/tor/torrc >/dev/null 2>&1
   touch /etc/tor/torrc >/dev/null 2>&1
   cat << 'EOT' > /etc/tor/torrc
       CookieAuthentication 0
       VirtualAddrNetworkIPv4 10.192.0.0/10
       AutomapHostsOnResolve 1
       AutomapHostsSuffixes .exit,.onion
       TransPort 127.0.0.1:9040
       DNSPort 127.0.0.1:5353
       ControlPort 9051
       EntryNodes {is},{ch},{fi},{ro}
       ExitNodes {is},{ch},{fi},{ro}
       StrictNodes 1
       MaxCircuitDirtiness 20
       ClientUseIPv6 0
       ClientPreferIPv6ORPORT 0
       ClientRejectInternalAddresses 1
EOT

echo -e "\n${P}[${WHITE}+${P}]${NC} Done"

shift
break
;;

--restart|-restart|restart|-r)
mode=11
if [ $EUID -ne 0 ]; then
    echo -e "\n${RED}[${NC}X${RED}]${NC} Run this as root"
    exit 1
fi

echo -e "\n${BLUE}[${NC}!${BLUE}]${P} Restarting Tor..${NC}"
      
pkill -9 tor >/dev/null 2>&1

config

shift
break
;;

--status|-status|status|-s)
mode=12

if pgrep -af tor >/dev/null 2>&1 || ss -tulpn | grep -iE "127.0.0.1|5353|9040|9050|9051" >/dev/null 2>&1; then
   nyx
else
   echo -e "\n${RED}[${NC}X${RED}]${NC} Tor is not running..."
   exit 1
fi

shift
break
;;

--help|-help|help|-h)

mode=13

help

shift

break

;;

--*|-*|*)
mode=14

echo -e "\n${RED}[${NC}!${RED}]${NC} Unknown action: '$1', run 'tonion --help', for detailed info"

exit 1

shift
break
;;

esac
done

# This dumb condition that throws a Help page

if [[ -z "$mode" ]]; then
    help
    echo -e "\n${RED}[${NC}!${RED}]${NC} Missing action"
    exit 1
fi
